### ISSUE TITLE
update the Digicert instructions with new Firefox layout

### ISSUE THREAD

**Issue by natalieda** [sara-nl/griddocs#41]
The instructions to export the Digicert X509 certificate from a Firefox browser [[griddocs/source/Pages/Basics/certificates/digicert.rst ] should be updated with the newer Firefox versions > v57.0 layout.  The 'Advanced' section is gone and certificates are now in 'Privacy & Security',  as explained in the DutchGrid instructions [ griddocs/source/Pages/Basics/certificates/dutchgrid.rst ].

**Comment by oonkjbr** [comment]
I have pushed the updated digicert info to my local githubinstance, see

https://github.com/oonkjbr/griddocs/blob/master/source/Pages/Basics/certificates/digicert.rst

how do we now push this to sara-nl?

**Comment by natalieda** [comment]
Thank you @oonkjbr. The changes have been now pushed in the public doc in 4387e1dd9eb8cdf2e11348a528aa482e9afb57e7
