### ISSUE TITLE
FTS server seems to not exist

### ISSUE THREAD

**Issue by ygrange** [sara-nl/griddocs#44]
In fts.rst, there is documentation on the existance of a SURFsara FTS instance, running on fts3.grid.sara.nl (with some direct links to ports and directories). Sems like that host does not exist (anymore). Was it moved, or discontinued? In either case this may need to be changed in the documentation :).

**Comment by natalieda** [comment]
Hi Yan,

We still support FTS (https://fts.grid.surfsara.nl:8449/fts3/). We need to update the documentation with the rights domains. Thank you for reporting this.

Best
Natalie

**Comment by ygrange** [comment]
Thanks Natalie (I replied to this message by email but that probably failed).

**Comment by natalieda** [comment]
The FTS documentation is now updated and enriched with API usage examples:
http://doc.grid.surfsara.nl/en/latest/Pages/Advanced/storage_clients/fts.html#fts

Best
Natalie
