### ISSUE TITLE
Data ingest service not mentioned?

### ISSUE THREAD

**Issue by onnozweers** [sara-nl/griddocs#5]
A search for "ingest" did not give any results:
http://doc.grid.surfsara.nl/en/latest/search.html?q=ingest&check_keywords=yes&area=default

Shouldn't the data ingest service be mentioned somewhere? What would be a good place?

**Comment by niekbosch** [comment]
Isn't that a separate service, which should have its own documentation?

**Comment by natalieda** [comment]
It is an independent service but it would be useful for Grid users with large data on disks to know that they can ingest the data to the Grid Storage. We can put a pointer in the Grid storage page to the service description here:
https://www.surf.nl/en/services-and-products/data-ingest-service/index.html

**Comment by onnozweers** [comment]
Followed Natalie's suggestion.
